### ISSUE TITLE
rev 1 errata

### ISSUE THREAD

**Issue by gkasprow** [elhep/AFCZ#1]
- [x] BSC050N03LSGATMA1CT-ND footprint is wrong - 5x6 instead of 3x3. Mounted CSD17308Q3 instead

**Comment by gkasprow** [comment]
- [ ] DNP R626
- [ ] swapped SDA with SCL on Exar 2 programming connector

**Comment by gkasprow** [comment]
- [ ] R289 = VCC

**Comment by gkasprow** [comment]
- [ ] add caps for 1.2V rail clock inputs.

**Comment by gkasprow** [comment]
- [ ] short reset pins 1 and 2 of IC56
![obraz](https://user-images.githubusercontent.com/4325054/49832907-46d4af00-fd98-11e8-8a9d-f7fdcf97e3c9.png)

**Comment by gkasprow** [comment]
Crystal oscillator frequency, do not use 48MHz, must be 33.33MHz.

**Comment by gkasprow** [comment]
- [ ] add pullup on ETH1 RX_CLK (PHY address)
- [ ] short ETH1 CRS  with ETH1 RX_DV

**Comment by krmac** [comment]
> 
> 
> Crystal oscillator frequency, do not use 48MHz, must be 33.33MHz.

Correct value is 50 MHz.

**Comment by filipswit** [comment]
@gkasprow could you please explain following:
 

-  R289 = VCC

- add caps for 1.2V rail clock inputs.
 

-----------------


> BSC050N03LSGATMA1CT-ND footprint is wrong - 5x6 instead of 3x3. Mounted CSD17308Q3 instead

Transistors (CSD17308Q3 ) are already changed.

>  short reset pins 1 and 2 of IC56

Jumper was added to IC56
![image](https://user-images.githubusercontent.com/24258965/84892055-31cb9100-b09d-11ea-9f5f-17c329833e38.png)

>  add pullup on ETH1 RX_CLK (PHY address)
 short ETH1 CRS with ETH1 RX_DV

Added jumper and pullup:
![image](https://user-images.githubusercontent.com/24258965/84892287-9555be80-b09d-11ea-8db0-4bcd8983af42.png)

**Comment by filipswit** [comment]
>  add caps for 1.2V rail clock inputs.

Where should I add caps?

**Comment by gkasprow** [comment]
All clock rails in the banks supplied from 1V2

**Comment by gkasprow** [comment]
they are clocked from 1V8 and common mode is far above 0.6V which is required by diff SSTL12

**Comment by filipswit** [comment]
ok, I haven't seen two clocks in SDRAM banks.

**Comment by gkasprow** [comment]
Can you open dedicated issues if you have some doubts? Otherwize we will miss important things.

**Comment by filipswit** [comment]
ok
