### ISSUE TITLE
Could we unify BC847 and BSS138?

### ISSUE THREAD

**Issue by marmeladapk** [elhep/AFCZ#100]
It saves a BoM line. While two BSS138 are marginally more expensive it shouldn't matter at these quantities. There's also enough space for two BSS138 in place of each BC847.

**Comment by gkasprow** [comment]
BC847 was used to sense low voltage rails which are below 1V. I'm not sure if BSS138 can do that. But it can be replaced by MOSFET that has low enough Vth

**Comment by filipswit** [comment]
BSS138 has Vth from 0.5 to 1.5V, so we will have to place there different Mosfet than BSS138 so anyway we won't save the BoM.  I leave it as is.
