### ISSUE TITLE
Should MMC TRSTn be connected to other TRSTn?

### ISSUE THREAD

**Issue by marmeladapk** [elhep/AFCZ#105]
Currently MMC TRSTn is connected directly to AMC_TRSTn and through diode to FMC1,2 and RTM.

IMO MMC TRSTn shouldn't be connected to FMC and RTM JTAG and should be connected to AMC JTAG only when P3V3 is low (the same condition as in IC12).

**Comment by gkasprow** [comment]
exactly. MMC won't be chained with other JTAG devices.

**Comment by filipswit** [comment]
So the solution is to add another analog switch same as IC12?

**Comment by gkasprow** [comment]
connect it to AMC JTAG only through DNP resistor.
