### ISSUE TITLE
EN_USB_JTAG should be connected directly to pin 13 od J6

### ISSUE THREAD

**Issue by marmeladapk** [elhep/AFCZ#107]
Now only disabling USB JTAG access works, enabling it back, when programmer disconnects and pin 13 of J6 is pulled up does not work.

~~(we can probably just remove D38)~~

D38 is needed to disable AMC access when programmer is inserted.

See connections on Sayma AMC:

![Zrzut ekranu z 2020-07-28 12-43-03@2x](https://user-images.githubusercontent.com/24512604/88656016-e8c12080-d0cf-11ea-9b2e-877704bba049.png)

EN_USB_JTAG is connected directly to pin 13 and additionally when programmer pulls low pin 13 then gate of T6 is pulled low and OE# of IC12 is high, disabling AMC access.

**Comment by filipswit** [comment]
Copied the above.
