### ISSUE TITLE
FMC+ connector

### ISSUE THREAD

**Issue by gkasprow** [elhep/AFCZ#12]
CERN asked:
Concerning the v2 of the board, would it still be possible to makes some small modifications, typically on clocking and up to when ?
 
A question aside, For now we will use the “FMC” versions of the AFCZ with 6.4 Gsps ADC FMCs but we were initially aiming at 10 Gsps which would require a FMC+ connector with minimum 10x12.5 Gbps lanes. Would it be of interest for you to have such a version of the AFCZ? In other words an AFCZ with one FMC+ connector with minimum 10 serial links routed and a standard one.

**Comment by filipswit** [comment]
Do we make any modifications with FMC+?

**Comment by gkasprow** [comment]
It's a lot of work.
We cannot increase the number of layers.
The suitable connectors are already in the CERN library. You can check if it is feasible without a serious redesign of the board.

**Comment by filipswit** [comment]
Mechanically it's possible;) But routing additional differential links doesn't look pleasantly.

**Comment by gkasprow** [comment]
LEt's ask CERN about the importance of this modification.

**Comment by kaolpr** [comment]
CERN:
> t is not a priority for this release. We prefer limiting the changes too as for now we will use the links as they are.

I think the issue can be closed for now.
