### ISSUE TITLE
Connect reset of GPIO expander to P3V3 through pullup

### ISSUE THREAD

**Issue by marmeladapk** [elhep/AFCZ#125]
IC52

Datasheet:

> Connect to VCC through a pull-up resistor if no active connection is used

**Comment by filipswit** [comment]
In which DS you found it?

**Comment by marmeladapk** [comment]
TCA9539
https://www.ti.com/lit/ds/symlink/tca9539.pdf#%5B%7B%22num%22%3A90%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C0%2C720%2C0%5D

**Comment by filipswit** [comment]
So this requirement applies to signals INT and RESET. In this DS is nothing about unused IOs.
