### ISSUE TITLE
VCU supply should be 0V9 not 0V85

### ISSUE THREAD

**Issue by marmeladapk** [elhep/AFCZ#144]
Additionally this supply cannot be shared with other supply rails:

> VCCINT_VCU is a 0.90V rail that provides power to the video codec unit (VCU) within Zynq UltraScale+ MPSoC EV devices. VCCINT_VCU must be powered as a standalone power rail and cannot be combined with any other power rails.

**Comment by filipswit** [comment]
@gkasprow are we going to use Video Codec version of ZynQ?

**Comment by filipswit** [comment]
I don't think that we are going to add another power supply, so I can connect VCU supply to P0V9_MGTAVCC or add test point for an external supply in case of EV version tests.
