### ISSUE TITLE
BoM - Availability

### ISSUE THREAD

**Issue by marmeladapk** [elhep/AFCZ#148]
Not available:

- 93LC56B-I/OT - I didn't find this combination of size and package
- MT40A512M16HA-083E:A - probably new revision is available
- PA0513.261NLT - MOQ is 2000
- Si571AJC000337DG
- Heatsink

Low availability:

- SG-310 SCN 50.0000MJ (50 MHz oscillator)
- KV7050B20.0000C3GD00

**Comment by filipswit** [comment]
- https://www.digikey.com/product-detail/en/microchip-technology/93LC56BT-I-OT/93LC56BT-I-OTCT-ND/857632

- I think we may change it to this: MT40A512M16LY-075:E

- This looks similar IFLR5151HZERR26M01

- Only one I found is this: https://pl.mouser.com/ProductDetail/Silicon-Labs/571FDB000159DG?qs=9zLto0EiZzGIqvjSKdsr6w%3D%3D it is  **2.5v** version 10-1417.5MHz and it's not cheap.

- changed to : SKV585811-CU

- changed to : 636L3I050M00000
 
- Is in Digikey, and expected in Mouser
