### ISSUE TITLE
Flash memory for user data connected to PL

### ISSUE THREAD

**Issue by kaolpr** [elhep/AFCZ#150]
CERN insists on having direct access to some non-volatile memory from PL to store WRC calibration data. 

Please add a separate flash connected to PL exclusively and make it an assembly variant.

**Comment by arthurspi** [comment]
Concerning this issue our prefered solution is having PS and PL pins connected to the same flash. I.e. shorting the PS & PL pins (post the TXB0108 buffers). This prove to work on our boards and allows for flashing over PCIe.

**Comment by filipswit** [comment]
@arthurspi Is this solution fine for you? Should Enable be driven from MMC, to switch between PS and PL access?

![image](https://user-images.githubusercontent.com/24258965/92909368-57133580-f427-11ea-9b27-ebf64c5e2080.png)

**Comment by arthurspi** [comment]
@filipswit The idea is to have access to the flash that holds the board's firmware from the PL. We don't actually need a second memory.
If we can apply the same circuit to the existing flash that would be perfect.

**Comment by filipswit** [comment]
@arthurspi If you want to use flash that already exist (IC37 IC40), don't you have access to it through FPGA_SPI_FLASH_UPDATE?

**Comment by arthurspi** [comment]
@filipswit The reason is there is a shared infrastructure at cern to flash over PCI, and it has a direct SPI interface as for the wr-core. 
by FPGA_SPI_FLASH_UPDATE do you mean the axi interface?

**Comment by filipswit** [comment]
There is an SPI connected to MMC and PL.
![image](https://user-images.githubusercontent.com/24258965/93576795-8ed82b00-f99b-11ea-89ad-358c6ee906bc.png)
![image](https://user-images.githubusercontent.com/24258965/93576830-9697cf80-f99b-11ea-8149-8ac9599159ab.png)

**Comment by arthurspi** [comment]
To my understanding there is one SPI connection between the MMC and the PL but not between PL and the QSPI flash

**Comment by filipswit** [comment]
@arthurspi sorry you are right, while making #84, just realized that there are two separate SPIs. I added another from PL to Flash.
