### ISSUE TITLE
FMC inrush current

### ISSUE THREAD

**Issue by kaolpr** [elhep/AFCZ#17]
Some FMCs can draw a significant current when FMC P12V is turned on. Gerd Kotzian at CERN made a measurement with FMC card of one of the leading manufacturers and obtained the following results:
![image](https://user-images.githubusercontent.com/9166701/83816442-adebcf00-a6c2-11ea-8255-73206b83d97f.png)
![image](https://user-images.githubusercontent.com/9166701/83816453-b3e1b000-a6c2-11ea-8952-12495fd6f2c8.png)
These were obtained when powering board with power connector. When board is placed in mTCA crate overcurrent limits of the power supply prevents AFCZ from powering up correctly.

One of tested solutions was adding 100 nF capacitor between gate and source of the MOSFET switch for FMC power supply line to limit inrush current. The following was observer by Gerd after application of the fix:
![image](https://user-images.githubusercontent.com/9166701/83816655-310d2500-a6c3-11ea-99f5-547b0504cd46.png)
Inrush current is significantly lower in this case, so probably this can be applied as a solution.

**Comment by filipswit** [comment]
Loks like already fixed. 
![image](https://user-images.githubusercontent.com/24258965/83870981-7b2bf000-a72f-11ea-9f05-ab916385c9bb.png)

**Comment by kaolpr** [comment]
@gkasprow Did you added this capacitor or CERN added another in parallel?

**Comment by gkasprow** [comment]
this value needs to be bigger than originally used. It's better to ask CERN about it. Maybe they added another 100nF and 200nF did the job.

**Comment by gkotzian** [comment]
Please note that a capacitor was added between gate and _DRAIN_, leaving the 100nF between gate and source unchanged. A value of 100nF did the job. Further details on this subject can be found [here](https://www.onsemi.com/pub/Collateral/AND9093-D.PDF).

LTSPICE circuit simulation:
![image](https://user-images.githubusercontent.com/66667417/84121497-89cc1d00-aa37-11ea-96a7-0325e0587279.png)
![image](https://user-images.githubusercontent.com/66667417/84121704-c8fa6e00-aa37-11ea-9d51-22f9cc2f43d9.png)

**Comment by filipswit** [comment]
@gkotzian thanks for correcting.
