### ISSUE TITLE
RTM I2C Bus Isolation an Pull-Ups

### ISSUE THREAD

**Issue by kaolpr** [elhep/AFCZ#20]
According to mTCA 4.1 specification RTM I2C bus should be separated by bidirectional buffer powered from P3V3_MP (REQ 3-7). 

RTM I2C pull-ups should be present only on RTM module, according to Figure 3-1.

**Comment by filipswit** [comment]
I2C mux is powered from P3V3MP, do we really need another buffer?

**Comment by gkasprow** [comment]
This is probably due to the fact that unpowered RTM will block it's I2C bus branch. The RTM 3V3MP is switched. Theoretically it's I2C could be switched as well.

**Comment by filipswit** [comment]
Added PCA9513 .

**Comment by gkasprow** [comment]
The easiest way of switching off the RTM I2C branch is connection of pullups to the P3V3_MP_RTM

**Comment by filipswit** [comment]
I've routed En pin to MMC.
