### ISSUE TITLE
88E6321 Configuration EEPROM

### ISSUE THREAD

**Issue by kaolpr** [elhep/AFCZ#22]
If #21 is resolved to leaving Marvell 88E6321 verify that EEPROM is connected properly.

**Comment by gkasprow** [comment]
I have a tool that generates the EEPROM configuration

**Comment by kaolpr** [comment]
Do you know if EEPROM size is correct?

**Comment by gkasprow** [comment]
I used same one as on the devkit.

**Comment by filipswit** [comment]
It seems to me that on devkit is used: S-24CS04.

**Comment by gkasprow** [comment]
what is used in the design?

**Comment by filipswit** [comment]
24LC024H-I/SN

**Comment by gkasprow** [comment]
No idea why I used it. It's better to replace it with the same PN

**Comment by filipswit** [comment]
An exact copy from dev kit is available only in different package (and it doesn't exist in libs), so I add it as an option.

**Comment by gkasprow** [comment]
it does not have to be an exact PN. The addressing and capacity must be the same.

**Comment by filipswit** [comment]
ok.
