### ISSUE TITLE
Standardize library to generate clean BOM

### ISSUE THREAD

**Issue by kaolpr** [elhep/AFCZ#28]
There's no standard library - some parts originate from CERN library, some are custom made. The use of a standardized library would greatly improve project maintainability and BOM readability. CERN library is preferred.

**Comment by filipswit** [comment]
I changing optional MMC storage from W25Q128JVSIM(industrial grade) to W25Q128FVSIG.

**Comment by gkasprow** [comment]
OK, I would mark it as DNP, to my knowledge, so far nobody used it.

**Comment by filipswit** [comment]
ok
