### ISSUE TITLE
Add assembly variant resistors to RTM_BANK_CLK_IN

### ISSUE THREAD

**Issue by kaolpr** [elhep/AFCZ#30]
![image](https://user-images.githubusercontent.com/9166701/83870951-6cddd400-a72f-11ea-9b4f-e6b61a81543b.png)
There is an unavoidable stub with those resistors missing.

**Comment by gkasprow** [comment]
can you show it on PCB?

**Comment by kaolpr** [comment]
Yeah, seems it looks way worst in schematics than in PCB. The stub is relatively short:
![image](https://user-images.githubusercontent.com/9166701/84063016-96f9f500-a9c0-11ea-9a57-dbb3b35e8cb9.png)

**Comment by filipswit** [comment]
Added:
![image](https://user-images.githubusercontent.com/24258965/84767240-60306a00-afd2-11ea-8c49-804d18b932c6.png)
