### ISSUE TITLE
Evaluate FPGA drop-in replacements

### ISSUE THREAD

**Issue by kaolpr** [elhep/AFCZ#31]
Check if XCZU11EG-2FFV1517E can be considered as an assembly variant. If so, update #15 accordingly.

**Comment by gkasprow** [comment]
we can skip EV version, we have so far very limited applications for it.
Make sure we include low-cost version used in DI/OT controller.

**Comment by filipswit** [comment]
![image](https://user-images.githubusercontent.com/24258965/85037145-42573680-b185-11ea-8cf3-6909eb7f18c2.png)
