### ISSUE TITLE
Clocking tree

### ISSUE THREAD

**Issue by kaolpr** [elhep/AFCZ#37]
There are several issues regarding clocking tree for AFCZ:

* it is quite complex what makes it not really straightforward to use,
* CERN has some requirements, that seem not to be met at the moment (will be discussed in the following comments to this issue)
* some unification with [AFC4 clocking tree](https://ohwr.org/project/afc/issues/43#note_116367) may be considered (taking into account presence of SoC)

As a starting point for the discussion let's take a diagram (hopefully accurate) of the current AFCZ clocking tree:

![AFCZ1v1_Clocking_rev0](https://user-images.githubusercontent.com/9166701/84877701-1f475c80-b089-11ea-92e7-550558e6422c.png)

If one wants to modify this diagram [yEd source is here](https://github.com/elhep/AFCZ/files/4791353/AFCZ1v1_Clocking_rev0.zip).

**Comment by gkasprow** [comment]
I would get rid of:
Si5324 - it will be replaced by DDMTD anyway
SY89540 and replace it by assembly option as in AFCv4
TCLKC and TCLKD optionally as an assembly option or not use at all.

**Comment by kaolpr** [comment]
Rev 1
![AFCZ1v1_Clocking_rev1](https://user-images.githubusercontent.com/9166701/84892999-d4384400-b09e-11ea-9971-2169bd35a83c.png)
If one wants to modify this diagram [yEd source is here](https://github.com/elhep/AFCZ/files/4792167/AFCZ1v1_Clocking_rev1.zip).
.

**Comment by filipswit** [comment]
May I start implementing Rev.1 to schematics?

**Comment by kaolpr** [comment]
It would be great if @gkasprow would approve it, but I think you can start implementing it.

You can swap clock matrix ports according to the layout constraints.

**Comment by gkasprow** [comment]
Looks good to me. Go ahead.

**Comment by kaolpr** [comment]
CERN reports that for their application a simultaneous use of:

* GTP8-11_CLK connected to clock matrix and
* MGT226 fed with WR clock.

Suggested resolution: connect CLK7 to MGT227 REFCLK0 with an assembly option to GTP4-7_CLK_IN/OUT.

**Comment by filipswit** [comment]
@kaolpr Could you please edit the diagram?

**Comment by kaolpr** [comment]
Yes, but after 18. I've uploaded the wrong file in the zip (PNG instead of diagram source) and I don't have access to that file right now.

**Comment by kaolpr** [comment]
![AFCZ1v1_Clocking_rev2](https://user-images.githubusercontent.com/9166701/85995144-41809900-b9fe-11ea-87de-59cea152874b.png)
Diagram source: [AFCZ1v1_Clocking_rev2.zip](https://github.com/elhep/AFCZ/files/4844874/AFCZ1v1_Clocking_rev2.zip)

**Comment by kaolpr** [comment]
- [ ] Invalid CLK11 connection
![image](https://user-images.githubusercontent.com/9166701/86458053-e95ed500-bd24-11ea-8f4b-05abb25424f8.png)
- [ ] Swapped FMC2_GBTCLK0_M2C with FMC2_GBTCLK1_M2C (connected to wrong MGT clocks)
- [ ] Don't think we really need control buffer to AMC_TCLK and uFL connector. They can be always-on.

There are also couple of missing assembly options, but these are still to be defined.

Why do you use `Undefined` values of resistors in some places?

**Comment by filipswit** [comment]
> Swapped FMC2_GBTCLK0_M2C with FMC2_GBTCLK1_M2C (connected to wrong MGT clocks)

Can we leave it as is? It's already routed on pcb? If not I'll swap it.

**Comment by kaolpr** [comment]
Yeah, we can keep it swapped.

**Comment by kaolpr** [comment]
One remark for routing - clock matrix ports can be assigned in a way that would be easier to route.
