### ISSUE TITLE
XCZU7 pinout differences

### ISSUE THREAD

**Issue by filipswit** [elhep/AFCZ#38]
There is a pinout difference between current XCZU7 component and one from CERNlib
![image](https://user-images.githubusercontent.com/24258965/85307721-8a8d9600-b4b0-11ea-9ae3-b507abe3144b.png)

From Xilinx page https://www.xilinx.com/support/packagefiles/zuppackages/xczu7cgffvf1517pkg.txt
seems that these pins should be tied to GND, but in current version they're tied to 0V85.

**Comment by gkasprow** [comment]
the actual part is probably re-named ZU7EV component which has VCU - video codec. LEt's add a 0R resistor and capacitors that are already connected to these pins.

**Comment by filipswit** [comment]
ok
