### ISSUE TITLE
FMC P3V3MP

### ISSUE THREAD

**Issue by kaolpr** [elhep/AFCZ#40]
P3V3MP is missing from FMC connectors.

**Comment by gkasprow** [comment]
It is called FMC1_POWER.3P3VAUX

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/86023564-23319200-ba2c-11ea-865e-ae9dca88bfa6.png)

**Comment by gkasprow** [comment]
Let's rename it to be consistent

**Comment by kaolpr** [comment]
What for is this assembly option?

**Comment by gkasprow** [comment]
some FMC modules, i.e. from 4DSP do not meet VITA recommendation. They consume much more current from P3V3MP than allowed.

**Comment by filipswit** [comment]
Renamed them to P3V3MP.1 and P3V3MP.2
