### ISSUE TITLE
Prevent MMC resets when opening terminal for controlling serial ports on Linux

### ISSUE THREAD

**Issue by kaolpr** [elhep/AFCZ#41]
See https://ohwr.org/project/afc/issues/134. Suggest implement it the same way.

**Comment by kaolpr** [comment]
This circuitry was decided to be greatly simplified in AFC4:
![image](https://user-images.githubusercontent.com/9166701/86890476-a5d9e180-c0fd-11ea-90c9-a8e0c99364c2.png)
Also having this approach implemented SW2 does not seem to be needed anymore.

**Comment by filipswit** [comment]
Did you have any issues with TXB level translator? Can I leave them or should swap to SN74AVC2T245?

**Comment by filipswit** [comment]
Actually we can skip SW2. Is this "bypass" needed? It goes to SW2.
![image](https://user-images.githubusercontent.com/24258965/86896292-0ff68480-c106-11ea-8bb9-029602cf3079.png)

**Comment by gkasprow** [comment]
this switch was used to enable operation outside of MTCA crate
