### ISSUE TITLE
P12V0_AUX (P12V_Molex) presence should disable reset

### ISSUE THREAD

**Issue by kaolpr** [elhep/AFCZ#43]
As in AFCv4:
![image](https://user-images.githubusercontent.com/9166701/86021458-63dbdc00-ba29-11ea-8d5c-902da76a1088.png)

**Comment by gkasprow** [comment]
Make sure that T16 Vth distribution ensures correct operation

**Comment by filipswit** [comment]
Vgs(th)max is 1.5V, so it's fine.
