### ISSUE TITLE
Support ETM tracing for MMC

### ISSUE THREAD

**Issue by kaolpr** [elhep/AFCZ#46]
As here: https://ohwr.org/project/afc/issues/126

**Comment by filipswit** [comment]
Placed 2x3pin 2.0mm header. If will be enough space will fit the same con as on AFCv4.0.

**Comment by kaolpr** [comment]
Maybe we could merge ETM connector with J1 to unify with AFC4:
![image](https://user-images.githubusercontent.com/9166701/86892801-06b6e900-c101-11ea-98da-42ac88287d75.png)

**Comment by filipswit** [comment]
Is it for sure standard pinout and connector?

**Comment by kaolpr** [comment]
When implemented this way it can be easily used with Segger debugger like this:
![image](https://user-images.githubusercontent.com/9166701/87165833-f9e5f100-c2ca-11ea-9cc9-b4f3653c37f9.png)

**Comment by filipswit** [comment]
ok
