### ISSUE TITLE
Power supply control and I2C mux reset during MMC reset 

### ISSUE THREAD

**Issue by kaolpr** [elhep/AFCZ#47]
As described here: https://ohwr.org/project/afc/issues/30 GPIO expander seems to be a more reliable approach than a latch. Additionaly, we can add IC29 reset to that expander implementing https://ohwr.org/project/afc/issues/143.

Maybe we could also give PL control over IC29 mux reset?

**Comment by filipswit** [comment]
Added the same expander. Implemented FPGA_MUX_Reset signals fom expander and PL through 0R.
