### ISSUE TITLE
USB Quad connections

### ISSUE THREAD

**Issue by filipswit** [elhep/AFCZ#50]
In AFC4 this circuit is greatly simplified
![image](https://user-images.githubusercontent.com/24258965/86895066-3ddac980-c104-11ea-8334-add3d2d8d26d.png)

Simplify it or leave it as is?

**Comment by gkasprow** [comment]
remove DNP resistors. IC16 may not be needed.

**Comment by filipswit** [comment]
Redesigned to that:
![image](https://user-images.githubusercontent.com/24258965/87031101-da739900-c1e2-11ea-91ec-d00e6f0dbf7d.png)

**Comment by kaolpr** [comment]
If SN74AVC2T245 were already introduced, maybe we could consider replacing TXB0304 with those? We don't need a bidirectional level translator here and TXB0304 seems to be a bit vulnerable to layout (glitches from reflections), what we've painfully experienced with FMC TDC card.

**Comment by gkasprow** [comment]
Yes, do it. The simpler, the better.

**Comment by filipswit** [comment]
Previously I haven't checked space (there will be 4 ICs instead of 2), but i looks fine.

**Comment by gkasprow** [comment]
Just copy it from Sayma/Kasli
