### ISSUE TITLE
SD card translator

### ISSUE THREAD

**Issue by marmeladapk** [elhep/AFCZ#53]
ST6G3244MEBJR is mounted by default. Weren't there many problems with soldering it?

**Comment by gkasprow** [comment]
Yes, it has 0.4mm BGA pitch. Other alternatives do not support the fastest SD standards. I'd add a slower alternative used on Xilinx devkit.

**Comment by kaolpr** [comment]
There were, but manufacturer has identified the source of the issue and claims that it should not be a problem anymore.

**Comment by gkasprow** [comment]
what was the source of the issue?
