### ISSUE TITLE
Unify SN74AVC2T245RSWR and TXB0304RUTR

### ISSUE THREAD

**Issue by marmeladapk** [elhep/AFCZ#59]
Could we unify SN74AVC2T245RSWR (only 2 pcs on AFCZ) and TXB0304RUTR? We could save a BoM line.

Price per port is comparable, however I don't think that having part with direction auto sensing is safe on JTAG lines so I would lean towards using SN74AVC2T245RSWR.

AFAICT no signal on TXB0304RUTR used in AFCZ is bidirectional so we don't need direction sensing.

**Comment by gkasprow** [comment]
definitely, we should avoid auto-direction sensing transceivers when possible.

**Comment by marmeladapk** [comment]
Besides, TXB0304RUTR datasheet states that:

> If pull-up or pull-down resistors are connected externally to the data I/Os,their values must be kept higher than 20 kΩ to ensure that they do not contend with the output drivers of the TXB0304.

On JTAG lines we use 10k pullups.

**Comment by gkasprow** [comment]
be careful with auto-sensing level translators and pullups/puuldowns. They can bring to unexpected issues. Just avoid such translators when possible

**Comment by kaolpr** [comment]
When replacing this:
![image](https://user-images.githubusercontent.com/9166701/87941039-ce1cf500-ca9a-11ea-8f5e-fb9f30198fb1.png)
please keep MMC master to maintain compatibility with AFCv4.
