### ISSUE TITLE
DTR and RTS lines on MMC console

### ISSUE THREAD

**Issue by marmeladapk** [elhep/AFCZ#62]
- AFAICT when FTDI is powered it actively pulls up DTR and RTS lines - this means that IC65 will pull down reset line to MMC unless one opens console and switches DTR and RTS lines
- btw DTR and RTS have pullups on FTDI side and pulldown on MMC side

Could we either implement circuit from Sayma or at least add switches to disconnect DTR and RTS lines? Or use XNOR instead or XOR gate (there still may be a problem when non-uniform pullup will cause short spike on reset line, so I'd be for an option of disconnecting those signals without soldering).

**Comment by filipswit** [comment]
It's a bug, there shouldn't be XOR.

**Comment by filipswit** [comment]
Placed AND gate - #63

**Comment by tprzywoz** [comment]
Why do we use AND gate here instead of XNOR like on AFC? There shouldn't be a problem with spikes because we use RC filter.
