### ISSUE TITLE
Shouldn't IC56 be an AND gate?

### ISSUE THREAD

**Issue by marmeladapk** [elhep/AFCZ#63]
So that when any reset source is asserted then it resets ULPI.

**Comment by gkasprow** [comment]
check it with xilinx devkit. It was copied directly from it.

**Comment by marmeladapk** [comment]
ZCU111 and ZCU104 have this:

![Zrzut ekranu z 2020-07-15 15 20 48](https://user-images.githubusercontent.com/24512604/87549969-cb8f5980-c6ae-11ea-9e3f-e6708822ee9d.png)

ZCU102:
![obraz](https://user-images.githubusercontent.com/24512604/87550603-87508900-c6af-11ea-8c73-8a67165c681f.png)

@gkasprow which one did you copy from? Any way they have AND gates, but do not use PS_SRST signal.

**Comment by gkasprow** [comment]
I don't remember. Let's use AND gate.
