### ISSUE TITLE
FPGA_MUX_Reset can be driven from two sources

### ISSUE THREAD

**Issue by marmeladapk** [elhep/AFCZ#88]
Two drivers are connected directly to each other.

Maybe change R95 or R544 to 200-300 Ohm to prevent short? It would also help then to change R286 to a larger value.

**Comment by filipswit** [comment]
@marmeladapk what do you think about adding AND gate?

**Comment by marmeladapk** [comment]
I think OR would be better. Or two transistors ORing this active low signal if adding OR would also add a BoM line. AND would require some additional communication between MMC and FPGA.
