### ISSUE TITLE
Unify GPIO expanders

### ISSUE THREAD

**Issue by marmeladapk** [elhep/AFCZ#89]
Can we remove IC70? It will save us a BoM line and we have enough pins on MMC to easily move all signals from expander to MMC.

**Comment by kaolpr** [comment]
No, this expander is there for a reason. It makes payload power persistent when MMC undergoes reset, see [AFCv4 discussion](https://ohwr.org/project/afc/issues/30).

**Comment by marmeladapk** [comment]
In that case unify this expander and IC52 (TCA9539RTWR)
