### ISSUE TITLE
JTAG CONFIG presence signals are not connected to actual presence signals

### ISSUE THREAD

**Issue by marmeladapk** [elhep/AFCZ#90]
This is a problem, because JTAG chain will be broken or will not automatically include plugged in devices.

- SOC_PS_PS# and Override_SOC_PS are 100% redundant (unless we find SOC PS signal on the board, could it be one of the GPIOs, which could signify that JTAG TAP is active?)
- SOC_PS_PS# should have a pull up/pull down
- FMC1/2_PS# should be connected to PRSNT signal from FMC1/2_MISC harness
- RTM_PS# from harness should be connected to RTM_PS# signal from RTM connector

Also remove duplicated connections to MMC.

**Comment by filipswit** [comment]
SOC_PS_PS# connected to PS I/O.
